# -*- coding: utf-8 -*-
"""FinansalVeriAnaliz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfsxrXK1DSqxoyqF-KrkHyE4N4OkzKTn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#tüm dosyaları birleştireceğiz.
files=['Apple.csv','Amazon.csv','Google.csv','Microsoft.csv','Netflix.csv']
all_data=[]

for file in files:
  temp_df=pd.read_csv(file)
  temp_df['Symbol']=file.split('.')[0] # dosya adından şirket adını alıyoruz
  all_data.append(temp_df)

df= pd.concat(all_data, ignore_index=True)

print("Temizlik öncesi")
print(f"Toplam satır:{len(df)}")
print(f"Eksik veri sayısı:\n{df.isnull().sum()}")
print("\nTekrar Eden Satır Sayısı:", df.duplicated().sum())

df.dropna(inplace=True) #boş satırları siliyoruz ( şuan boş bir satırımız yok ama ilerde eklenecek herhangibir dosyayı da hesap etmen lazım)
df.drop_duplicates(inplace=True) # tekrar eden satırları siliyoruz
df.sort_values(by=['Symbol', 'Date'], inplace=True)# tarihe göre dizilim yaptık
print(df.head())

df['Daily_Return']=df.groupby('Symbol')['Close'].transform(lambda x: x.pct_change()*100)

df['SMA50']= df.groupby('Symbol')['Close'].transform(lambda x: x.rolling(window=50).mean())
df['SMA200']=df.groupby('Symbol')['Close'].transform(lambda x: x.rolling(window=200).mean())

print("Finansal metrikler daily rutin sma50 sma200 hesaplandı")

votality=df.groupby('Symbol')['Daily_Return'].std()

print("Şirket bazlı risk analizi ( votalite)")
print(votality.sort_values(ascending=False))
print("\n Not: Voralite ne kadar yüksekse rişk o kadar fazladır")

#fiyat karşılaştırma
plt.figure(figsize=(12,6))
for symbol in df['Symbol'].unique():
  subset = df[df['Symbol'] == symbol]
  plt.plot(subset['Date'], subset['Close'], label=symbol)

plt.title('MAANG HİSSE FİYATLARI (2000-2023)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

#ısı haritası
pivot_df = df.pivot(index='Date', columns='Symbol', values='Close')
plt.figure(figsize=(8, 6))
sns.heatmap(pivot_df.corr(), annot=True, cmap='RdYlGn')
plt.title('Şirketlerin Birbirine Bağımlılık Haritası')
plt.show()